# syntax=docker/dockerfile:1.4

# debian 12 (bookworm).
FROM debian:12-slim

# install dependencies.
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends \
  postgresql-client-common \
  python3-psycopg2
rm -rf /var/lib/apt/lists/*
EOF

# install the binaries.
COPY --chmod=0755 test-postgres.py /usr/local/bin/test-postgres

# set the entrypoint.
ENTRYPOINT ["/usr/local/bin/test-postgres", "quote"]
