# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  postgres:
    # see https://hub.docker.com/_/postgres
    # see https://github.com/docker-library/postgres/tree/master/16/bookworm
    image: postgres:16-bookworm
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
  init:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.init
    # see https://www.postgresql.org/docs/16/libpq-envars.html
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - QUOTES_WRITER_USERNAME=bob
      - QUOTES_WRITER_PASSWORD=bob
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/.tfstate/terraform.log
    volumes:
      - .:/.tfstate
  test:
    depends_on:
      - init
      - postgres
    build:
      dockerfile: Dockerfile.test
    # see https://www.postgresql.org/docs/16/libpq-envars.html
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=alice
      - PGPASSWORD=alice
      - PGDATABASE=quotes
